apiVersion: batch/v1
kind: Job
metadata:
  name: s3-smoke-test
  namespace: my-app
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: tester
          image: python:3.11-alpine
          command:
            - sh
            - -lc
            - |
              pip install --no-cache-dir boto3 >/dev/null 2>&1
              python - <<'PY'
              import os, boto3, botocore, sys
              AWS_ENDPOINT = os.getenv("AWS_ENDPOINT")
              AWS_REGION = os.getenv("AWS_REGION", "eu-west-1")
              BUCKET = os.getenv("S3_BUCKET", "my-app-bucket")
              s3 = boto3.client(
                  "s3",
                  endpoint_url=AWS_ENDPOINT,
                  aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID", "test"),
                  aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY", "test"),
                  region_name=AWS_REGION,
                  config=botocore.config.Config(s3={"addressing_style": "path"}),
              )
              key = "hello.txt"
              body = b"Hello from Kubernetes via LocalStack S3!"
              print(f"Uploading s3://{BUCKET}/{key} ...")
              s3.put_object(Bucket=BUCKET, Key=key, Body=body)
              print("Listing objects:")
              resp = s3.list_objects_v2(Bucket=BUCKET)
              for obj in resp.get("Contents", []):
                  print("-", obj["Key"], obj["Size"], "bytes")
              print("Downloading object:")
              obj = s3.get_object(Bucket=BUCKET, Key=key)
              data = obj["Body"].read()
              print("Content:", data.decode())
              print("SUCCESS")
              PY
          env:
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: test
            - name: AWS_REGION
              value: eu-west-1
            - name: AWS_ENDPOINT
              value: http://localstack.default.svc.cluster.local:4566
            - name: S3_BUCKET
              value: my-app-bucket
